<?php

/**
 * @file
 * WebService Content module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function xtcfile_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.xtcfile':
      $variables = [
        ':xtcfile' => Url::fromRoute('help.page', ['name' => 'xtcfile'])->toString(),
      ];

      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The <a href=":xtcfile">WebService Content for Dummy sources</a> module provide features to pull contents from Dummy source.', $variables) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<p>' . t('[to be completed]') . '</p>';

      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function xtcfile_theme($existing, $type, $theme, $path) {
  return [
    'xtc_file' => [
      'variables' =>  ['response' => NULL],
      'template' => 'xtc-file',
    ],
  ];
}
