<?php

/**
 * @file
 * WebService Content module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\xtc\XtendedContent\API\Config;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function xtcfile_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.main':
      $output = '<h2>' . t('Documentation') .
                '</h2>';
      $output .= '<p>' . t('Readme files and Documentation pages can be directly consulted from 
the administration area.') . '</p>';
      $output .= '<p>' . t('<a href=":documentation">This page</a> lists links to Readme files included in 
the modules packages, and Documentation based on <b><a href=":mkdocs" target="_blank">MkDocs</a></b> standards.',
                           [':documentation' => Url::fromRoute('xtcfile.docs')->toString(), ':mkdocs' => 'https://www.mkdocs.org/']) . '</p>';
      return ['#markup' => $output];
    case 'help.page.xtcfile':
      return Config::getHelp('xtcfile');
  }
}

/**
 * Implements hook_theme().
 */
function xtcfile_theme($existing, $type, $theme, $path) {
  return [
    'xtc_file' => [
      'variables' =>  ['response' => NULL],
      'template' => 'xtc-file',
    ],
    'xtc_documentation' => [
      'variables' =>  [
        'links' => NULL
      ],
      'template' => 'xtc-documentation',
    ],
    'xtc_docs_links' => [
      'variables' =>  [
        'name' => '',
        'help' => '',
        'docs' => '',
        'readme' => '',
      ],
      'template' => 'xtc-docs-links',
    ],
    'xtc_mkdocs' => [
      'variables' =>  ['response' => NULL],
      'template' => 'xtc-mkdocs',
    ],
    'xtc_mkdocs_page' => [
      'variables' =>  ['response' => NULL],
      'template' => 'xtc-mkdocs-page',
    ],
  ];
}
